services:
  fintree-postgres:
    restart: unless-stopped
    image: postgres:18-alpine
    container_name: fintree-postgres
    environment:
      POSTGRES_DB: fin_tree
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fintree-net

  fintree.api:
    restart: unless-stopped
    container_name: fintree-api
    build:
      context: .
      dockerfile: FinTree.Api/Dockerfile
    image: fintree.api:local
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Production"
      Auth__JwtSecretKey: ${AUTH_JWT_SECRET_KEY}
      Auth__Issuer: ${AUTH_ISSUER}
      Auth__Audience: ${AUTH_AUDIENCE}
      Auth__TokenLifetimeDays: ${AUTH_TOKEN_LIFETIME_DAYS}
      Telegram__BotToken: ${TELEGRAM_BOT_TOKEN}
      ConnectionStrings__DefaultConnection: ${CONNECTION_STRINGS_DEFAULT}
      FxRates__ApiKey: ${FXRATES_API_KEY}
    depends_on:
      - fintree-postgres
    networks:
      - fintree-net

  fintree.nginx:
    restart: unless-stopped
    container_name: fintree-nginx
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
      args:
        VITE_API_BASE_URL: "/api"
    image: fintree.nginx:local
    ports:
      - "80:80"
    depends_on:
      - fintree.api
    networks:
      - fintree-net

volumes:
  pgdata:

networks:
  fintree-net:
    driver: bridge
