# This is a generated file. Not intended for manual editing.
services:
  fintree.api:
    build:
      context: "/Users/nranenko/Desktop/Projects/FinTree"
      dockerfile: "FinTree.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57401"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "fintree.api:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57401"
    volumes:
    - "/Users/nranenko/Desktop/Projects/FinTree/FinTree.Api:/app:rw"
    - "/Users/nranenko/Desktop/Projects/FinTree:/src:rw"
    - "/Users/nranenko/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/nranenko/.local/share/JetBrains/RiderRemoteDebugger/2025.3.1/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/nranenko/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_1_15_20_05_13:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
