# This is a generated file. Not intended for manual editing.
services:
  fintree.api:
    build:
      context: "/Users/nranenko/Desktop/Projects/FinTree"
      dockerfile: "FinTree.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/FinTree.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "fintree.api:dev"
    ports: []
    volumes:
    - "/Users/nranenko/Desktop/Projects/FinTree/FinTree.Api:/app:rw"
    - "/Users/nranenko/Desktop/Projects/FinTree:/src:rw"
    - "/Users/nranenko/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
